export const GAME_STATUS = {
  WAIT: 'WAIT',
  VOTE: 'VOTE',
  APPROVE: 'APPROVE',
  SELECT_TASK_PLAYER: 'SELECT_TASK_PLAYER',
  SELECT_REVEAL_PLAYER: 'SELECT_TASK_RESULT',
  SELECT_KILL_PLAYER: 'SELECT_KILL_PLAYER',
  ASSIGN_GOD_STATEMENT: 'ASSIGN_GOD_STATEMENT',
};
